# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSSFeeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeditems',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='feeditems',
            unique_together=set([('title', 'url')]),
        ),
    ]
