# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSFeeds', '0002_auto_20160323_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditems',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='feeditems',
            unique_together=set([]),
        ),
    ]
